
# SEO settings
title: "Think"
title2: "Write" 
# default: ""
description: "My personal blog"
keywords: "blog,technology,tech,Parth Verma,IIT"
url: http://parth-vader.github.io/ # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/parth-vader/parth-vader.github.io
disqus_shortname: ""
twitter_username: "VaderParth"
comments: true 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Parth Verma"
  job      : "Maths and Computing student, IIT Kharagpur"
  bio      : "I try to learn something everyday"
  thumb    : /images/author.jpg
  email    : vermaparth97@gmail.com
  url      : http://parth-vader.github.io
  github   : http://github.com/parth-vader
  twitter  : http://twitter.com/VaderParth
  facebook : https://www.facebook.com/ParthVerma4
  linkedin : https://www.linkedin.com/in/parth-verma-a57847108/

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@VaderParth"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
